### ISSUE TITLE
Multi Language Database Support

### ISSUE THREAD

**Issue by im-gugogi** [iPzard/media-file-renamer#18]
The TMDB contains movie/TV information in various languages.

But I think only English databases are available in this program.

Is there a function to select the language of the database?

Thank you.

**Comment by iPzard** [comment]
Thanks for reporting! I'll look into this.

**Comment by iPzard** [comment]
Unfortunately, I don't see any options for this with the [TVMaze Public API](https://www.tvmaze.com/api), which is what's used with this program.
